- name: Create persistent volume for mysql
  shell: docker volume create "{{ env }}-mysql"

- name: Deploy Mysql container
  docker_container:
    name: "{{ env }}-mysql"
    image: mysql:5.7
    ports:
      - "{{ mysql_host_port }}:3306"
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    volumes:
      - "{{ env }}-mysql:/var/lib/mysql"
    recreate: yes
    detach: yes

- name: Create persistent volume for redis
  shell: docker volume create "{{ env }}-redis"

- name: Deploy Redis container
  docker_container:
    name: "{{ env }}-redis"
    image: redis:latest
    ports:
      - "{{ redis_host_port }}:6379"
    volumes:
      - "{{ env }}-redis:/data"
    restart_policy: always
    recreate: yes
    detach: yes

- name: Wait for services to start
  pause: seconds=10

