template_path: dev/bastionHost.yaml
dependencies:
  - dev/eks.yaml
parameters:
  InstanceImage: "{{ stack_group_config.bastion_image_id }}"
  SSHKey: "{{ stack_group_config.ssh_key_name }}"
  VmType: "{{ stack_group_config.bastion_instance_type }}"
  SubnetPublicId: !stack_output dev/vpc.yaml::SubnetPublic
  BastionSecurityGroup: !stack_output dev/vpc.yaml::BastionSecurityGroup
  ClusterName: "{{ stack_group_config.cluster_name }}"
  awsConfig: !file_contents /root/.aws/config
  awsCredentials: !file_contents /root/.aws/credentials
  ### monitoring stack config
  GrafanaUser: "{{ stack_group_config.GrafanaUser }}"
  GrafanaPassword: "{{ stack_group_config.GrafanaPassword }}"
  GrafanaKey: "{{ stack_group_config.GrafanaKey }}"
  InfluxUser: "{{ stack_group_config.InfluxUser }}"
  InfluxPassword: "{{ stack_group_config.InfluxPassword }}"
  InfluxDb: "{{ stack_group_config.InfluxDb }}"
  OpsgenieApiKey: "{{ stack_group_config.OpsgenieApiKey }}"
  OpsgenieUrl: "{{ stack_group_config.OpsgenieUrl }}"
  OpsgenieEnabled: "{{ stack_group_config.OpsgenieEnabled }}"
  TelegrafUser: "{{ stack_group_config.TelegrafUser }}"
  TelegrafPassword: "{{ stack_group_config.TelegrafPassword }}"
  TeamName: "{{ stack_group_config.TeamName }}"
  Environment: "{{ stack_group_config.Environment }}"
  DnsZoneId: "{{ stack_group_config.DnsZoneId }}"
