template_path: dev/eks.yaml
parameters:
  ClusterName: "{{ stack_group_config.cluster_name }}"
  ClusterVersion: "{{ stack_group_config.cluster_version }}"
  SubnetPrivate1: !stack_output dev/vpc.yaml::SubnetPrivate1
  SubnetPrivate2: !stack_output dev/vpc.yaml::SubnetPrivate2
  VPCID: !stack_output dev/vpc.yaml::VpcId
  VpcCidr: "{{ stack_group_config.vpc_cidr }}"
  WorkersDesiredCount: "{{ stack_group_config.workers_desired_count }}"
  WorkersMaxCount: "{{ stack_group_config.workers_max_count }}"
  WorkerInstanceType: "{{ stack_group_config.worker_instance_type }}"
  WorkerSshKey: "{{ stack_group_config.ssh_key_name }}"
  WorkerDiskSize: "{{ stack_group_config.worker_disk_size }}"
  BastionSg: !stack_output dev/vpc.yaml::BastionSecurityGroup
  SubnetPublic: !stack_output dev/vpc.yaml::SubnetPublic
  SubnetPublic2: !stack_output dev/vpc.yaml::SubnetPublic2

