- name: Gracefully shutting down queue worker..
  shell: docker exec -it "{{ env }}-queue" php artisan horizon:terminate
  ignore_errors: yes
  no_log: True

- pause: seconds=5

- name: Deploy Queue worker service
  docker_container:
    name: "{{ env }}-queue"
    image: "{{ queue_image }}"
    restart_policy: on-failure
    volumes:
      - "/etc/thetool-{{ env }}/env:/usr/share/nginx/html/.env"
    command: queue
    recreate: yes
    detach: yes

